tshirtstore/config/routes.rb
Tshirtstore::Application.routes.draw do
  resources :brands

 post '/shirts/' => 'shirts#create', :as => :create_shirt
         get '/shirts/', :to => 'shirts#index', :as => 'shirts'
         get '/shirts/new', :to => 'shirts#new'
         get '/shirts/:id', :to => 'shirts#show', :as => 'shirt'

end

tshirtstore/app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :shirts
  attr_accessible :country, :name
end

tshirtstore/app/models/shirt.rb
class Shirt < ActiveRecord::Base
	belongs_to :brand
  attr_accessible :color, :description, :price, :size
end

tshirtstore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

tshirtstore/app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @brands }
    end
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @brand = Brand.find(params[:id])
    @shirts = @brand.shirts.sort_by {|shirt| shirt.color}
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/new
  # GET /brands/new.json
  def new
    @brand = Brand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @brand }
    end
  end

  # GET /brands/1/edit
  def edit
    @brand = Brand.find(params[:id])
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(params[:brand])

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render json: @brand, status: :created, location: @brand }
      else
        format.html { render action: "new" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /brands/1
  # PUT /brands/1.json
  def update
    @brand = Brand.find(params[:id])

    respond_to do |format|
      if @brand.update_attributes(params[:brand])
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url }
      format.json { head :no_content }
    end
  end
end

tshirtstore/app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  def index
  @shirts=Shirt.all()
  end

  def show
    @shirt = Shirt.find(params[:id])
  end

  def new
    @shirt=Shirt.new()
  end

  def edit
  end

  def create
                @shirt = Shirt.new(params[:shirt])
                if @shirt.save
                        redirect_to @shirt
                else
                        # This line overrides the default rendering behavior, which
                        # would have rendered the "create" view, which doesn't exist.
                        render :action => "new"
                end
        end
end

tshirtstore/app/helpers/application_helper.rb
module ApplicationHelper
end

tshirtstore/app/helpers/brands_helper.rb
module BrandsHelper
end

tshirtstore/app/helpers/shirts_helper.rb
module ShirtsHelper
end

tshirtstore/app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tshirtstore/app/views/brands/edit.html.erb
<h1>Editing brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

tshirtstore/app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Country</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @brands.each do |brand| %>
  <tr>
    <td><%= brand.name %></td>
    <td><%= brand.country %></td>
    <td><%= link_to 'Show', brand %></td>
    <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
    <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Brand', new_brand_path %>

tshirtstore/app/views/brands/new.html.erb
<h1>New brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

tshirtstore/app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @brand.name %>
</p>

<p>
  <b>Country:</b>
  <%= @brand.country %>
</p>


<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>

tshirtstore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tshirtstore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

tshirtstore/app/views/shirts/edit.html.erb
<h1>Shirts#edit</h1>
<p>Find me in app/views/shirts/edit.html.erb</p>

tshirtstore/app/views/shirts/index.html.erb
<h1>All Shirts</h1>
<table>
        <tr>
                <td>Color</td>
                <td>Size</td>
                <td>Description</td>
                <td>Price</td>
        </tr>
        <% @shirts.each do |shirt| %>
                <tr>
                        <td><%= shirt.color %></td>
                        <td><%= shirt.size %></td>
                        <td><%= shirt.description %></td>
                        <td>£<%= shirt.price %></td>
                </tr>
        <% end %>
</table>
<%= link_to "New Shirt", :action => "new" %>

tshirtstore/app/views/shirts/new.html.erb
<h1>New Shirt</h1>
<%= form_for(@shirt) do |f| %>
        <%= f.label :color %><br />
        <%= f.text_field :color %><br />
        <%= f.label :size %><br />
        <%= f.text_field :size %><br />
        <%= f.label :description %><br />
        <%= f.text_area :description %><br />
        <%= f.submit %>
        <%= f.label :price %><br />
        <%= f.text_field :price %><br />
<% end %>

tshirtstore/app/views/shirts/show.html.erb
<h1>View Shirt</h1>
        Color: <%= @shirt.color %><br />
        Size: <%= @shirt.size %><br />
        Description: <%= @shirt.description %><br />
        Price: <%= @shirt.price %><br /><br />
        <%= link_to "Back to All Shirts", :action => "index" %>
<% @shirts.each do |shirt| %>
<p><%= shirt.color %> (<%= shirt.size %>)</p>
<% end %>